name: Faction CD Workflow

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.repository.default_branch }}
        fetch-depth: 0
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Clean and Compile the project
      run: mvn clean compile
    
    - name: Package WAR file
      run: mvn war:war
    
    - name: Configure Git
      run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote rm origin
          git remote add origin git@github.com:${{ github.repository }}.git
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.RELEASE_IT_SSH_PRIVATE_KEY }}
    - name: Force add WAR file
      run: git add -f ./target/*.war
    
    - name: Commit and Push WAR file
      run: |
        git commit -m "Deploying WAR file - $(date)"
        git push
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'artifacts' # Specify the same branch here
